dist: bionic
language: python
python:
  - "3.7"
addons:
  chrome: stable
cache: pip

before_install:
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - wget -N "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose
  - pip install flake8

before_script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

# command to run tests
script:
  - chromedriver --version
  - pip freeze
  - nosetests ./tests --with-coverage --cover-package=app --cover-xml --verbose --nologcapture
after_success:
  - coverage combine
  - coveralls
